# Generated by Django 5.1.4 on 2025-01-25 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginify_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetails',
            new_name='UserDetail',
        ),
    ]
